// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATtNp8dAdGMkD7WgOudc28p7el_QQmYx8',
    appId: '1:515704589681:web:b6763f18a09e9db803fad0',
    messagingSenderId: '515704589681',
    projectId: 'flash-char-app-with-flutter',
    authDomain: 'flash-char-app-with-flutter.firebaseapp.com',
    storageBucket: 'flash-char-app-with-flutter.appspot.com',
    measurementId: 'G-606GMRWWYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2WRjXxVsrjd8UTRi-5bJm-oCUBgBe4EA',
    appId: '1:515704589681:android:5ef28a9ddd22424203fad0',
    messagingSenderId: '515704589681',
    projectId: 'flash-char-app-with-flutter',
    storageBucket: 'flash-char-app-with-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZYAGlmIb-t0EeFr8sKBHo0rxEsXnI2Fc',
    appId: '1:515704589681:ios:7e7bbc29ce127e5503fad0',
    messagingSenderId: '515704589681',
    projectId: 'flash-char-app-with-flutter',
    storageBucket: 'flash-char-app-with-flutter.appspot.com',
    iosBundleId: 'com.example.flashChatApp',
  );
}
